production:
  bucket: <%= ENV['AWS_BUCKET'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>

staging:
  bucket: <%= ENV['AWS_BUCKET'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>

development:
  bucket: <%= ENV['AWS_BUCKET'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>  #
  secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
